# Generated by Django 5.1.6 on 2025-05-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='excel_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/%Y/%m/%d/%H-%M-%S/'),
        ),
        migrations.AlterField(
            model_name='uploadedexcel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
