# Generated by Django 5.1.6 on 2025-06-02 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0002_alter_uploadedexcel_excel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
