# Generated by Django 5.1.6 on 2025-03-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0003_businessapprovedlist_uploadedfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_config_name', models.CharField(blank=True, max_length=255, null=True)),
                ('configuration_files_count', models.IntegerField(blank=True, null=True)),
                ('business_approved_count', models.IntegerField(blank=True, null=True)),
                ('files_matched', models.IntegerField(blank=True, null=True)),
                ('remaining_files', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessapprovedlist',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='businessapprovedlist',
            name='config_type',
        ),
        migrations.AddField(
            model_name='businessapprovedlist',
            name='configuration_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessapprovedlist',
            name='configuration_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessapprovedlist',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessapprovedlist',
            name='file_name_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessapprovedlist',
            name='hrl_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessapprovedlist',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
