# Generated by Django 5.1.6 on 2025-06-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0003_alter_uploadedexcel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedexcel',
            name='approved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedexcel',
            name='pending_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedexcel',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
