# Generated by Django 5.1.6 on 2025-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0004_uploadedexcel_approved_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedexcel',
            name='filtration_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
