# Generated by Django 5.1.6 on 2025-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0005_storedexcel_delete_businessapprovedlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
