# Generated by Django 5.1.6 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0006_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='folder_name',
            field=models.CharField(default='default_folder', max_length=255),
        ),
    ]
