# Generated by Django 5.1.6 on 2025-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0007_uploadedfile_file_data_alter_uploadedfile_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
