# Generated by Django 5.1.6 on 2025-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0008_alter_uploadedfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
