# Generated by Django 5.1.6 on 2025-05-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0010_uploadedexcel_delete_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedexcel',
            name='file',
        ),
    ]
