# Generated by Django 5.1.6 on 2025-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0011_remove_uploadedexcel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='excel_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
