# Generated by Django 5.1.6 on 2025-05-06 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0012_alter_uploadedexcel_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedexcel',
            name='file_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedexcel',
            name='status',
            field=models.CharField(default='Processed', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedexcel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
