# Generated by Django 5.1.6 on 2025-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0013_uploadedexcel_file_name_uploadedexcel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedexcel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedexcel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='uploadedexcel',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
