# Generated by Django 5.1.6 on 2025-05-08 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0014_remove_uploadedexcel_uploaded_at_uploadedexcel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedexcel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
