# Generated by Django 5.1.6 on 2025-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0015_uploadedexcel_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/%H-%M-%S/'),
        ),
    ]
