# Generated by Django 5.1.6 on 2025-05-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0016_alter_uploadedexcel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedexcel',
            name='stored_excel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Macro.storedexcel'),
        ),
    ]
