# Generated by Django 5.1.6 on 2025-05-11 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0017_uploadedexcel_stored_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedexcel',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='storedexcel',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
