# Generated by Django 5.1.6 on 2025-05-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0019_alter_storedexcel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedexcel',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
