# Generated by Django 5.1.6 on 2025-05-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macro', '0020_alter_storedexcel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedexcel',
            name='file',
        ),
        migrations.AlterField(
            model_name='storedexcel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
